### ISSUE TITLE
Add the ability to add a context image as the background

### ISSUE THREAD

**Issue by amy-keibler** [amy-keibler/blog-opengraph-image#14]
Given a config of

``` toml
[extra]
og_background = "./context_image.png"
```

Perform the following operations:

- Crop / scale the image to the right dimensions if needed (from the center)
  - Warn when cropping and scaling
- overlay the text background block
- overlay the border
